stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: user-manager-front
  DOCKER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

containerization:
  stage: containerization
  script:
    - cp ${ENV} ./.env.production
    - >
      docker build
      --build-arg HTTP_PROXY=$HTTP_PROXY
      --build-arg HTTPS_PROXY=$HTTPS_PROXY
      -t ${DOCKER_IMAGE}
      .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE} # Cleanup

deployment:
  stage: deployment
  script:
    - envsubst < deployment.yml | kubectl apply -f -
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
