stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: user-manager-front

  CONTAINER_REGISTRY: ${DOCKER_HUB_USERNAME}
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_TAG}

  K8S_INGRESS_HOST: users.maximemoreillon.com

# Needed for Docker in docker build
image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

build:
  stage: build
  tags:
    - dind
  only:
    - tags
  before_script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    # Building the container image
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    # Pushing the image to the registry
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  only:
    - tags
  stage: deploy
  tags:
    - dind
  before_script:
    - kubectl config use-context moreillon_ci/moreillon_k8s/kubernetes-agent:cloud
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -n ${KUBERNETES_NAMESPACE} -f -
